const projects = [
  {
    id: "stock-management",
    title: "Stock Management PWA",
    shortDescription:
      "Inventory tool with barcode scanning, sales tracking, and PWA support.",
    description:
      "A stock management system designed for retail shops and warehouses. It supports QR/Barcode scanning, sales recording, monthly reporting, and can be installed as an app (PWA-like).",
    stack: [
      "React + TypeScript",
      "Chakra UI",
      "Supabase",
      "Barcode scanning: @zxing/browser",
      "Vite + vite-plugin-pwa",
    ],
    imageUrl: "/portfolio/images/projects/stock-management/stock-demo.png",
    demoUrl: "https://minimarmo.github.io/stock-management",
    sourceUrl: "https://github.com/minimarmo/stock-management",
  },
  //   {
  //     id: "e-commerce",
  //     title: "E-Commerce Platform",
  //     shortDescription: "",
  //     description: "",
  //     stack: [],
  //     imageUrl: "/portfolio/images/placeholder.png",
  //     demoUrl: "",
  //     sourceUrl: "",
  //   },
  //   {
  //     id: "leasing-management",
  //     title: "Leasing Management",
  //     shortDescription: "",
  //     description: "",
  //     stack: [],
  //     imageUrl: "/portfolio/images/placeholder.png",
  //     demoUrl: "",
  //     sourceUrl: "",
  //   },
  //   {
  //     id: "company-landing-page",
  //     title: "Company Landing Page",
  //     shortDescription: "",
  //     description: "",
  //     stack: [],
  //     imageUrl: "/portfolio/images/placeholder.png",
  //     demoUrl: "",
  //     sourceUrl: "",
  //   },
  //   {
  //     id: "habit-tracker",
  //     title: "Habit Tracker",
  //     shortDescription: "",
  //     description: "",
  //     stack: [],
  //     imageUrl: "/portfolio/images/placeholder.png",
  //     demoUrl: "",
  //     sourceUrl: "",
  //   },
  //   {
  //     id: "nocodb-api-gateway",
  //     title: "NOCODB Api Gateway",
  //     shortDescription: "",
  //     description: "",
  //     stack: [],
  //     imageUrl: "/portfolio/images/placeholder.png",
  //     demoUrl: "",
  //     sourceUrl: "",
  //   },
  {
    id: "qgis-plugin",
    title: "Polygon to Point (QGIS Plugin)",
    shortDescription:
      "แปลงข้อมูล Polygon เป็น Point พร้อมเลือก field ที่ต้องการได้ใน QGIS",
    description:
      "ปลั๊กอินสำหรับ QGIS ที่ช่วยแปลงเลเยอร์ข้อมูลแบบ Polygon ให้เป็น Point อย่างง่ายดาย พร้อมความสามารถในการเลือก field ที่ต้องการคัดลอก และกำหนดชื่อ field ใหม่ในผลลัพธ์ ใช้งานผ่าน GUI โดยตรงใน QGIS โดยไม่ต้องเขียนโค้ด",
    stack: ["Python", "PyQGIS", "Qt", "QGIS"],
    imageUrl: "/portfolio/images/projects/qgis-plugin/4_Fill_Data.png",
    demoUrl: "",
    sourceUrl: "https://github.com/minimarmo/polygon-to-point",
  },
  //   {
  //     id: "approval-app",
  //     title: "Approval App",
  //     shortDescription: "",
  //     description: "",
  //     stack: [],
  //     imageUrl: "/portfolio/images/placeholder.png",
  //     demoUrl: "",
  //     sourceUrl: "",
  //   },
  //   {
  //     id: "employee-dashboard",
  //     title: "Employee dashboard",
  //     shortDescription: "",
  //     description: "",
  //     stack: [],
  //     imageUrl: "/portfolio/images/placeholder.png",
  //     demoUrl: "",
  //     sourceUrl: "",
  //   },
];

export default projects;
